services:
  - type: web
    name: mafia
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne mafia.asgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "mafia.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: mafia-db
          property: connectionString

databases:
  - name: mafia-db
    plan: free
