services:
  - type: web
    name: mafia
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "daphne mafia.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mafia.settings
    plan: free
    webSocketSupport: true  # ✅ Add this line
