# Generated by Django 5.2.3 on 2025-06-22 20:41

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.generate_room_code, max_length=8, unique=True)),
                ('host_name', models.CharField(max_length=200)),
                ('config', models.JSONField(default=dict)),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, choices=[('Imposter', 'Imposter'), ('Villager', 'Villager'), ('Doctor', 'Doctor'), ('Policeman', 'Policeman')], max_length=20, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_host', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.gameroom')),
            ],
        ),
    ]
